version: '3.8'

services:
  meine-stimme-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped